[package]
org = "samples"
name = "carinbb_sample"
version = "0.1.0"
distribution = "2201.7.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "samples"
name = "sample.carinbb"
version = "1.0.0"
repository = "local"

[[dependency]]
org = "ballerinax"
name = "healthcare.fhir.r4"
version = "4.0.0"

# [[dependency]]
# org = "testabcd"
# name = "healthcare.fhir.aubase"
# version = "0.0.1"
# repository = "local"

# [[dependency]]
# org = "ballerinax"
# name = "healthcare.fhir.davincipayerdataexchange"
# version = "0.0.1"
# repository = "local"
