[package]
org = "isuruuy"
name = "carinbb_test"
version = "0.1.0"
distribution = "2201.7.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "healthcare.fhir.carinconsumerdirectedpayerdataexchange"
version = "0.0.1"
repository = "local"

# [[dependency]]
# org = "testabcd"
# name = "healthcare.fhir.aubase"
# version = "0.0.1"
# repository = "local"

# [[dependency]]
# org = "ballerinax"
# name = "healthcare.fhir.davincipayerdataexchange"
# version = "0.0.1"
# repository = "local"
