[package]
org = "isuruuy"
name = "carinbb_test"
version = "0.1.0"
distribution = "2201.7.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "wso2people"
name = "fhircarinbb"
version = "0.0.1"
repository = "local"
